[sdl]
fullscreen=false
output=surface
[mixer]
nosound=true
[cpu]
core=auto
cycles=max
[autoexec]
mount c /home/cdef/_PROJETS/ace/tools/dosbox-verify
c:
ACE.EXE a -y -std -s- -m3 BLK_H_DOS.ACE HELLO.TXT > OUT_H.TXT
exit
