                                         Copyright by Marcel Lemke, August 2005

  Informacja o licencji na archiwizer ACE v2.6
 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

      Pakiet dystrybucyjny ACE-a powinein zawiera† przynajmniej nast©puj¥ce
      pliki:

       ACE.EXE, ACE32.EXE, ACE2.EXE, UNACE.EXE, ACE.DOC, LICENSE.DOC,
       REGISTER.DOC, oraz REGISTER.FRM

      Termin "ACE" odnosi si© do caˆego w/wym. pakietu plik¢w.

      Oryginalne pakiety ACE-a tworzone s¥ tylko przez Marcela Lemke lub
      autoryzowanych dystrybutor¢w.


        1. Autor  nie  ponosi  odpowiedzialno˜ci  za  utrat©  danych, czasu,
           prywatnych  b¥d« sˆu¾bowych informacji ani za inne szkody wynikˆe
           z  u¾ycia b¥d« niemo¾no˜ci u¾ycia ACE-a lub jakiegokolwiek z jego
           skˆadnik¢w.


        2. Wszelkie prawa s¥ zastrze¾one przez Marcela Lemke, autora ACE-a.


        3. ACE wymaga zarejestrowania tak w przypadku prywatnego u¾ytku, jak
           i  komercyjnego.  Nie  zezwala  si© na rozpowszechnianie archiw¢w
           utworznych przy pomocy niezarejestrowanej kopii ACE-a.


        4. Aby u¾ywa† ACE-a po upˆywie 30-dniowego okresu pr¢bnego trzeba go
           zarejestrowa†.


        5. Rejestruj¥c   posiadan¥   kopi©  ACE-a  uzyskuje  si©  prawo  jej
           u¾ywania. Klucz rejestracyjny b©dzie dziaˆaˆ a¾ do zmiany systemu
           jego  weryfikacji.  Aktualizacja  klucza mo¾e wymaga† niewielkiej
           opˆaty. Liczba zarejestrownych kopii ACE-a jest ograniczona typem
           nabytej licencji.


        6. Zarejestrowana   kopia  ACE-a  nie  mo¾e  by†  przekazana  osobom
           trzecim.


        7. Wolno  rozpowszechnia†  tylko  oryginalne niezarejestrowane kopie
           ACE-a.  Za rozopwszechnianie nie wolno pobiera† opˆat oraz nale¾y
           zaznaczy†, ¾e jest to niezarejestrowana kopia produktu shareware.
           Produkt (ACE) musi zosta† zarejestrowany po 30 dniach u¾ywania.


        8. Nie  zezwala  si©  na  sprzeda¾  ACE-a,  modyfikacj© plik¢w w nim
           zawartych,    ani   odtwarzanie   ("reverse   engineering")   czy
           deasemblacj© jego plik¢w wykonywalnych.


        9. Prawo   u¾ywania  ACE-a  wymaga  akceptacji  warunk¢w  tej  umowy
           licencyjnej.


      Marcel Lemke, autor ACE-a
