
  +---------------------------------+   Read ORDER.TXT for more information!
  |  e-merge GmbH                   |   This form expires on January 1, 2005.
  |  Friedrich-Ebert Str. 157       |   
  |                                 |
  |  D-48153 Muenster               |                       Date:___________
  |  GERMANY                        | 
  |                                 |
  |  Phn +49-251-43000              |
  |  Fax +49-251-43052              | Signature:____________________________
  +---------------------------------+ 
    Name:                                      Phone: 
    ________________________________________   _____________________________
    (Company/Institution):                     (Email): 
    ________________________________________   _____________________________
    Address: 
    ________________________________________________________________________
    Zip/Country:                               (FAX):
    ________________________________________   _____________________________

    I wish to get a licence for use of the commandline ACE archiver

     [ ] on one computer (1 CPU) ...................... $29   _______
     [ ] on    2 to    4 CPUs ... number of CPUs: ___ x $24   _______
     [ ] on    5 to    9 CPUs     number of CPUs: ___ x $19   _______
     [ ] on   11 to   49 CPUs     number of CPUs: ___ x $17   _______
     [ ] on   60 to   99 CPUs     number of CPUs: ___ x $14   _______

    For larger amounts please contact a registration site directly.
    Visit us at http://www.winace.com fot a list of resellers.

    Shipping of files:

     [ ] by regular mail................................ $5   _______
     [ ] by email....................................... $0
          (Address must be given in the fields above!)      ___________

						    TOTAL: US$
                                                              =======
   -------------------------------------------------------------------------
    You have to specify an authenticity verification string:
    (please read the file ACE.DOC for information about this)

     _______________________________________________________________________
     (min: 10 chars; max: 50 chars; pay attention to upper and lower case)

   -------------------------------------------------------------------------

    Method of payment:

     [ ] Bank transfer to the following account:
           e-merge GmbH, Sparkasse Muenster, BLZ 400 501 50
           account nr. 17 006 834, purpose "ACE registration"
     [ ] Cheque
     [ ] Cash (add money to this order, maximum is $63)
     [ ] Credit card          [ ] Eurocard   [ ] VISA
     
           _______________________________   _______________________________
           Cardholder                        Signature
         
           _______________________________   _______________________________
           Credit card number                Expiry date
  
